// auto-generated by schema_gen

#include <stddef.h>
#include <stdint.h>

#define se_flags(x) (*(uint32_t *)x)
#define se_exists(x, f) (se_flags (x) & SE_##f##_exists)
#define se_clear(x, f) (se_flags (x) &= ~SE_##f##_exists)
#define se_set(x, f) (se_flags (x) |= SE_##f##_exists)
#define se_true(x, f) (se_flags (x) & SE_##f##_true)
#define se_set_true(x, f) (se_flags (x) |= SE_##f##_true)
#define se_set_false(x, f) (se_flags (x) &= ~SE_##f##_true)

// global flags
#define SE_description_exists (1 << 0)

typedef uint64_t SE_UInt48_t;
typedef uint8_t SE_UInt8_t;
typedef SE_UInt8_t SE_PhaseCode_t;
typedef SE_UInt8_t SE_KindType_t;
typedef uint32_t SE_UInt32_t;
typedef SE_UInt8_t SE_FlowDirectionType_t;
typedef SE_UInt8_t SE_DataQualifierType_t;
typedef SE_UInt8_t SE_CommodityType_t;
typedef int32_t SE_Int32_t;
typedef SE_UInt8_t SE_UomType_t;
typedef int8_t SE_Int8_t;
typedef SE_Int8_t SE_PowerOfTenMultiplierType_t;

typedef struct {
  SE_PowerOfTenMultiplierType_t multiplier;
  SE_UomType_t unit;
  SE_Int32_t value;
} SE_UnitValueType_t;

typedef SE_UInt8_t SE_AccumulationBehaviourType_t;

// #define SE_description_exists (1 << 0)
#define SE_subscribable_exists (1 << 1)
#define SE_version_exists (1 << 2)
#define SE_lFDI_exists (1 << 3)
#define SE_TimeLink_exists (1 << 4)
typedef struct {
  uint32_t _flags;
  char * href;
} SE_Resource_t;

#define SE_uom_exists (1 << 5)
#define SE_tieredConsumptionBlocks_true (1 << 6)
#define SE_tieredConsumptionBlocks_exists (1 << 7)
#define SE_supplyLimit_exists (1 << 8)
#define SE_subIntervalLength_exists (1 << 9)
#define SE_powerOfTenMultiplier_exists (1 << 10)
#define SE_phase_exists (1 << 11)
#define SE_numberOfTouTiers_exists (1 << 12)
#define SE_numberOfConsumptionBlocks_exists (1 << 13)
#define SE_maxNumberOfIntervals_exists (1 << 14)
#define SE_intervalLength_exists (1 << 15)
#define SE_flowDirection_exists (1 << 16)
#define SE_dataQualifier_exists (1 << 17)
#define SE_conversionFactor_exists (1 << 18)
#define SE_commodity_exists (1 << 19)
#define SE_calorificValue_exists (1 << 20)
#define SE_accumulationBehaviour_exists (1 << 21)
#define SE_kind_exists (1 << 22)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_AccumulationBehaviourType_t accumulationBehaviour;
  SE_UnitValueType_t calorificValue;
  SE_CommodityType_t commodity;
  SE_UnitValueType_t conversionFactor;
  SE_DataQualifierType_t dataQualifier;
  SE_FlowDirectionType_t flowDirection;
  SE_UInt32_t intervalLength;
  SE_KindType_t kind;
  SE_UInt8_t maxNumberOfIntervals;
  SE_UInt8_t numberOfConsumptionBlocks;
  SE_UInt8_t numberOfTouTiers;
  SE_PhaseCode_t phase;
  SE_PowerOfTenMultiplierType_t powerOfTenMultiplier;
  SE_UInt32_t subIntervalLength;
  SE_UInt48_t supplyLimit;
  SE_UomType_t uom;
} SE_ReadingType_t;

typedef SE_UInt8_t SE_SubscribableType_t;
typedef int64_t SE_Int48_t;
typedef SE_UInt8_t SE_TOUType_t;
typedef int64_t SE_Int64_t;
typedef SE_Int64_t SE_TimeType_t;

typedef struct {
  SE_UInt32_t duration;
  SE_TimeType_t start;
} SE_DateTimeInterval_t;

typedef uint8_t SE_HexBinary16_t[2];
typedef SE_UInt8_t SE_ConsumptionBlockType_t;

#define SE_value_exists (1 << 5)
#define SE_touTier_exists (1 << 6)
#define SE_timePeriod_exists (1 << 7)
#define SE_qualityFlags_exists (1 << 8)
#define SE_consumptionBlock_exists (1 << 9)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_ConsumptionBlockType_t consumptionBlock;
  SE_HexBinary16_t qualityFlags;
  SE_DateTimeInterval_t timePeriod;
  SE_TOUType_t touTier;
  SE_Int48_t value;
} SE_ReadingBase_t;

// #define SE_subscribable_exists (1 << 1)
// #define SE_value_exists (1 << 5)
// #define SE_touTier_exists (1 << 6)
// #define SE_timePeriod_exists (1 << 7)
// #define SE_qualityFlags_exists (1 << 8)
// #define SE_consumptionBlock_exists (1 << 9)
#define SE_localID_exists (1 << 10)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_ConsumptionBlockType_t consumptionBlock;
  SE_HexBinary16_t qualityFlags;
  SE_DateTimeInterval_t timePeriod;
  SE_TOUType_t touTier;
  SE_Int48_t value;
  SE_SubscribableType_t subscribable;
  SE_HexBinary16_t localID;
} SE_Reading_t;

typedef uint16_t SE_UInt16_t;
typedef SE_UInt16_t SE_VersionType_t;
typedef char SE_String32_t[32];
typedef uint8_t SE_HexBinary128_t[16];
typedef SE_HexBinary128_t SE_mRIDType_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
} SE_IdentifiedObject_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_DateTimeInterval_t timePeriod;
} SE_ReadingSetBase_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_DateTimeInterval_t timePeriod;
  List *Reading;
} SE_MirrorReadingSet_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
} SE_MeterReadingBase_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_ReadingType_exists (1 << 5)
#define SE_Reading_exists (1 << 6)
#define SE_nextUpdateTime_exists (1 << 7)
#define SE_lastUpdateTime_exists (1 << 8)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_TimeType_t lastUpdateTime;
  List *MirrorReadingSet;
  SE_TimeType_t nextUpdateTime;
  SE_Reading_t Reading;
  SE_ReadingType_t ReadingType;
} SE_MirrorMeterReading_t;

typedef uint8_t SE_HexBinary160_t[20];
typedef SE_UInt8_t SE_ServiceKind_t;
typedef SE_HexBinary16_t SE_RoleFlagsType_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_RoleFlagsType_t roleFlags;
  SE_ServiceKind_t serviceCategoryKind;
  SE_UInt8_t status;
} SE_UsagePointBase_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_postRate_exists (1 << 5)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_RoleFlagsType_t roleFlags;
  SE_ServiceKind_t serviceCategoryKind;
  SE_UInt8_t status;
  SE_HexBinary160_t deviceLFDI;
  List *MirrorMeterReading;
  SE_UInt32_t postRate;
} SE_MirrorUsagePoint_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
} SE_List_t;

#define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *MirrorUsagePoint;
} SE_MirrorUsagePointList_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *MirrorMeterReading;
} SE_MirrorMeterReadingList_t;

typedef uint64_t SE_UInt64_t;
typedef uint8_t SE_HexBinary48_t[6];

#define SE_maxRetryDuration_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  SE_UInt16_t maxRetryDuration;
  SE_UInt16_t reasonCode;
} SE_Error_t;

typedef uint8_t SE_HexBinary8_t;

// #define SE_description_exists (1 << 0)
#define SE_responseRequired_exists (1 << 5)
typedef struct {
  uint32_t _flags;
  char * href;
  char * replyTo;
  SE_HexBinary8_t responseRequired;
} SE_RespondableResource_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
// #define SE_responseRequired_exists (1 << 5)
typedef struct {
  uint32_t _flags;
  char * href;
  char * replyTo;
  SE_HexBinary8_t responseRequired;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
} SE_RespondableIdentifiedObject_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_Link_t;

#define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_NotificationListLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_MeterReadingLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_EndDeviceLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_DeviceCapabilityLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_DERProgramLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_DERLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_CustomerAccountLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ActiveFlowReservationListLink_t;

typedef struct {
  SE_PowerOfTenMultiplierType_t multiplier;
  SE_UInt16_t value;
} SE_UnsignedFixedPointType_t;

typedef int16_t SE_Int16_t;

typedef struct {
  SE_PowerOfTenMultiplierType_t multiplier;
  SE_Int16_t value;
} SE_FixedPointType_t;

typedef struct {
  SE_TimeType_t dateTime;
  SE_UInt8_t value;
} SE_StorageModeStatusType_t;

typedef SE_UInt16_t SE_PerCent_t;

typedef struct {
  SE_TimeType_t dateTime;
  SE_PerCent_t value;
} SE_StateOfChargeStatusType_t;

typedef struct {
  SE_TimeType_t dateTime;
  SE_UInt8_t value;
} SE_OperationalModeStatusType_t;

typedef char SE_String6_t[6];

typedef struct {
  SE_TimeType_t dateTime;
  SE_String6_t value;
} SE_ManufacturerStatusType_t;

typedef struct {
  SE_TimeType_t dateTime;
  SE_UInt8_t value;
} SE_LocalControlModeStatusType_t;

typedef struct {
  SE_TimeType_t dateTime;
  SE_UInt8_t value;
} SE_InverterStatusType_t;

typedef struct {
  SE_TimeType_t dateTime;
  SE_HexBinary8_t value;
} SE_ConnectStatusType_t;

// #define SE_description_exists (1 << 0)
// #define SE_subscribable_exists (1 << 1)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
} SE_SubscribableResource_t;

// #define SE_subscribable_exists (1 << 1)
#define SE_storConnectStatus_exists (1 << 5)
#define SE_storageModeStatus_exists (1 << 6)
#define SE_stateOfChargeStatus_exists (1 << 7)
#define SE_operationalModeStatus_exists (1 << 8)
#define SE_manufacturerStatus_exists (1 << 9)
#define SE_localControlModeStatus_exists (1 << 10)
#define SE_inverterStatus_exists (1 << 11)
#define SE_genConnectStatus_exists (1 << 12)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_ConnectStatusType_t genConnectStatus;
  SE_InverterStatusType_t inverterStatus;
  SE_LocalControlModeStatusType_t localControlModeStatus;
  SE_ManufacturerStatusType_t manufacturerStatus;
  SE_OperationalModeStatusType_t operationalModeStatus;
  SE_TimeType_t readingTime;
  SE_StateOfChargeStatusType_t stateOfChargeStatus;
  SE_StorageModeStatusType_t storageModeStatus;
  SE_ConnectStatusType_t storConnectStatus;
} SE_DERStatus_t;

typedef SE_UInt8_t SE_PrimacyType_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_DERCurveListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_DERControlListLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_DefaultDERControlLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ActiveDERControlListLink_t;

// #define SE_description_exists (1 << 0)
// #define SE_subscribable_exists (1 << 1)
// #define SE_version_exists (1 << 2)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
} SE_SubscribableIdentifiedObject_t;

// #define SE_description_exists (1 << 0)
// #define SE_subscribable_exists (1 << 1)
// #define SE_version_exists (1 << 2)
#define SE_DERCurveListLink_exists (1 << 5)
#define SE_DERControlListLink_exists (1 << 6)
#define SE_DefaultDERControlLink_exists (1 << 7)
#define SE_ActiveDERControlListLink_exists (1 << 8)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_ActiveDERControlListLink_t ActiveDERControlListLink;
  SE_DefaultDERControlLink_t DefaultDERControlLink;
  SE_DERControlListLink_t DERControlListLink;
  SE_DERCurveListLink_t DERCurveListLink;
  SE_PrimacyType_t primacy;
} SE_DERProgram_t;

// #define SE_subscribable_exists (1 << 1)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
} SE_SubscribableList_t;

// #define SE_subscribable_exists (1 << 1)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *DERProgram;
} SE_DERProgramList_t;

typedef SE_UInt8_t SE_DERUnitRefType_t;
typedef SE_UInt8_t SE_DERCurveType_t;

typedef struct {
  SE_Int32_t xvalue;
  SE_Int32_t yvalue;
} SE_CurveData_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_rampPT1Tms_exists (1 << 5)
#define SE_rampIncTms_exists (1 << 6)
#define SE_rampDecTms_exists (1 << 7)
#define SE_openLoopTms_exists (1 << 8)
#define SE_CurveData_count(x) (((se_flags (x) >> 9) & 0xf) + 1)
#define SE_set_CurveData_count(x, n) (se_flags(x) |= (((n) - 1) & 0xf) << 9)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_TimeType_t creationTime;
  SE_CurveData_t CurveData[10];
  SE_DERCurveType_t curveType;
  SE_UInt16_t openLoopTms;
  SE_UInt16_t rampDecTms;
  SE_UInt16_t rampIncTms;
  SE_UInt16_t rampPT1Tms;
  SE_PowerOfTenMultiplierType_t xMultiplier;
  SE_PowerOfTenMultiplierType_t yMultiplier;
  SE_DERUnitRefType_t yRefType;
} SE_DERCurve_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *DERCurve;
} SE_DERCurveList_t;

typedef struct {
  SE_PowerOfTenMultiplierType_t multiplier;
  SE_Int16_t value;
} SE_ActivePower_t;

typedef struct {
  SE_PowerOfTenMultiplierType_t multiplier;
  SE_Int16_t value;
} SE_ReactivePower_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_DERCurveLink_t;

typedef struct {
  SE_UInt32_t dBOF;
  SE_UInt32_t dBUF;
  SE_UInt16_t kOF;
  SE_UInt16_t kUF;
  SE_UInt16_t openLoopTms;
} SE_FreqDroopType_t;

typedef SE_Int16_t SE_SignedPerCent_t;

typedef struct {
  SE_DERUnitRefType_t refType;
  SE_SignedPerCent_t value;
} SE_FixedVar_t;

typedef struct {
  SE_Int16_t displacement;
  SE_PowerOfTenMultiplierType_t multiplier;
} SE_PowerFactor_t;

#define SE_rampTms_exists (1 << 0)
#define SE_opModWattVar_exists (1 << 1)
#define SE_opModWattPF_exists (1 << 2)
#define SE_opModVoltWatt_exists (1 << 3)
#define SE_opModVoltVar_exists (1 << 4)
#define SE_opModTargetW_exists (1 << 5)
#define SE_opModTargetVar_exists (1 << 6)
#define SE_opModMaxLimW_exists (1 << 7)
#define SE_opModLVRTMustTrip_exists (1 << 8)
#define SE_opModLVRTMomentaryCessation_exists (1 << 9)
#define SE_opModLFRTMustTrip_exists (1 << 10)
#define SE_opModHVRTMustTrip_exists (1 << 11)
#define SE_opModHVRTMomentaryCessation_exists (1 << 12)
#define SE_opModHFRTMustTrip_exists (1 << 13)
#define SE_opModFreqWatt_exists (1 << 14)
#define SE_opModFreqDroop_exists (1 << 15)
#define SE_opModFixedW_exists (1 << 16)
#define SE_opModFixedVar_exists (1 << 17)
#define SE_opModFixedPF_exists (1 << 18)
#define SE_opModEnergize_true (1 << 19)
#define SE_opModEnergize_exists (1 << 20)
#define SE_opModConnect_true (1 << 21)
#define SE_opModConnect_exists (1 << 22)
typedef struct {
  uint32_t _flags;
  SE_PowerFactor_t opModFixedPF;
  SE_FixedVar_t opModFixedVar;
  SE_SignedPerCent_t opModFixedW;
  SE_FreqDroopType_t opModFreqDroop;
  SE_DERCurveLink_t opModFreqWatt;
  SE_DERCurveLink_t opModHFRTMustTrip;
  SE_DERCurveLink_t opModHVRTMomentaryCessation;
  SE_DERCurveLink_t opModHVRTMustTrip;
  SE_DERCurveLink_t opModLFRTMustTrip;
  SE_DERCurveLink_t opModLVRTMomentaryCessation;
  SE_DERCurveLink_t opModLVRTMustTrip;
  SE_PerCent_t opModMaxLimW;
  SE_ReactivePower_t opModTargetVar;
  SE_ActivePower_t opModTargetW;
  SE_DERCurveLink_t opModVoltVar;
  SE_DERCurveLink_t opModVoltWatt;
  SE_DERCurveLink_t opModWattPF;
  SE_DERCurveLink_t opModWattVar;
  SE_UInt16_t rampTms;
} SE_DERControlBase_t;

typedef SE_Int16_t SE_OneHourRangeType_t;
typedef char SE_String192_t[192];

#define SE_reason_exists (1 << 0)
#define SE_potentiallySupersededTime_exists (1 << 1)
#define SE_potentiallySuperseded_true (1 << 2)
typedef struct {
  uint32_t _flags;
  SE_UInt8_t currentStatus;
  SE_TimeType_t dateTime;
  SE_TimeType_t potentiallySupersededTime;
  SE_String192_t reason;
} SE_EventStatus_t;

// #define SE_description_exists (1 << 0)
// #define SE_subscribable_exists (1 << 1)
// #define SE_version_exists (1 << 2)
// #define SE_responseRequired_exists (1 << 5)
typedef struct {
  uint32_t _flags;
  char * href;
  char * replyTo;
  SE_HexBinary8_t responseRequired;
  SE_SubscribableType_t subscribable;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
} SE_RespondableSubscribableIdentifiedObject_t;

// #define SE_description_exists (1 << 0)
// #define SE_subscribable_exists (1 << 1)
// #define SE_version_exists (1 << 2)
// #define SE_responseRequired_exists (1 << 5)
typedef struct {
  uint32_t _flags;
  char * href;
  char * replyTo;
  SE_HexBinary8_t responseRequired;
  SE_SubscribableType_t subscribable;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_TimeType_t creationTime;
  SE_EventStatus_t EventStatus;
  SE_DateTimeInterval_t interval;
} SE_Event_t;

// #define SE_description_exists (1 << 0)
// #define SE_subscribable_exists (1 << 1)
// #define SE_version_exists (1 << 2)
// #define SE_responseRequired_exists (1 << 5)
#define SE_randomizeStart_exists (1 << 6)
#define SE_randomizeDuration_exists (1 << 7)
typedef struct {
  uint32_t _flags;
  char * href;
  char * replyTo;
  SE_HexBinary8_t responseRequired;
  SE_SubscribableType_t subscribable;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_TimeType_t creationTime;
  SE_EventStatus_t EventStatus;
  SE_DateTimeInterval_t interval;
  SE_OneHourRangeType_t randomizeDuration;
  SE_OneHourRangeType_t randomizeStart;
} SE_RandomizableEvent_t;

// #define SE_description_exists (1 << 0)
// #define SE_subscribable_exists (1 << 1)
// #define SE_version_exists (1 << 2)
// #define SE_responseRequired_exists (1 << 5)
// #define SE_randomizeStart_exists (1 << 6)
// #define SE_randomizeDuration_exists (1 << 7)
typedef struct {
  uint32_t _flags;
  char * href;
  char * replyTo;
  SE_HexBinary8_t responseRequired;
  SE_SubscribableType_t subscribable;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_TimeType_t creationTime;
  SE_EventStatus_t EventStatus;
  SE_DateTimeInterval_t interval;
  SE_OneHourRangeType_t randomizeDuration;
  SE_OneHourRangeType_t randomizeStart;
  SE_DERControlBase_t DERControlBase;
} SE_DERControl_t;

// #define SE_subscribable_exists (1 << 1)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *DERControl;
} SE_DERControlList_t;

typedef SE_UInt8_t SE_DERType_t;

typedef struct {
  SE_PowerOfTenMultiplierType_t multiplier;
  SE_UInt16_t value;
} SE_WattHour_t;

typedef struct {
  SE_PowerOfTenMultiplierType_t multiplier;
  SE_UInt16_t value;
} SE_ApparentPower_t;

typedef struct {
  SE_PowerOfTenMultiplierType_t multiplier;
  SE_UInt16_t value;
} SE_AmpereHour_t;

typedef struct {
  SE_PowerOfTenMultiplierType_t multiplier;
  SE_UInt16_t value;
} SE_CurrentRMS_t;

typedef uint8_t SE_HexBinary32_t[4];
typedef SE_HexBinary32_t SE_DERControlType_t;

#define SE_rtgWh_exists (1 << 5)
#define SE_rtgVarNeg_exists (1 << 6)
#define SE_rtgVar_exists (1 << 7)
#define SE_rtgVA_exists (1 << 8)
#define SE_rtgUnderExcitedW_exists (1 << 9)
#define SE_rtgUnderExcitedPF_exists (1 << 10)
#define SE_rtgOverExcitedW_exists (1 << 11)
#define SE_rtgOverExcitedPF_exists (1 << 12)
#define SE_rtgNormalCategory_exists (1 << 13)
#define SE_rtgMinPFNeg_exists (1 << 14)
#define SE_rtgMinPF_exists (1 << 15)
#define SE_rtgMaxDischargeRateW_exists (1 << 16)
#define SE_rtgMaxDischargeRateVA_exists (1 << 17)
#define SE_rtgMaxChargeRateW_exists (1 << 18)
#define SE_rtgMaxChargeRateVA_exists (1 << 19)
#define SE_rtgAh_exists (1 << 20)
#define SE_rtgAbnormalCategory_exists (1 << 21)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_DERControlType_t modesSupported;
  SE_CurrentRMS_t rtgA;
  SE_UInt8_t rtgAbnormalCategory;
  SE_AmpereHour_t rtgAh;
  SE_ApparentPower_t rtgMaxChargeRateVA;
  SE_ActivePower_t rtgMaxChargeRateW;
  SE_ApparentPower_t rtgMaxDischargeRateVA;
  SE_ActivePower_t rtgMaxDischargeRateW;
  SE_PowerFactor_t rtgMinPF;
  SE_PowerFactor_t rtgMinPFNeg;
  SE_UInt8_t rtgNormalCategory;
  SE_PowerFactor_t rtgOverExcitedPF;
  SE_ActivePower_t rtgOverExcitedW;
  SE_PowerFactor_t rtgUnderExcitedPF;
  SE_ActivePower_t rtgUnderExcitedW;
  SE_ApparentPower_t rtgVA;
  SE_ReactivePower_t rtgVar;
  SE_ReactivePower_t rtgVarNeg;
  SE_ActivePower_t rtgW;
  SE_WattHour_t rtgWh;
  SE_DERType_t type;
} SE_DERCapability_t;

// #define SE_subscribable_exists (1 << 1)
#define SE_statWAvail_exists (1 << 5)
#define SE_statVarAvail_exists (1 << 6)
#define SE_reservePercent_exists (1 << 7)
#define SE_reserveChargePercent_exists (1 << 8)
#define SE_maxChargeDuration_exists (1 << 9)
#define SE_availabilityDuration_exists (1 << 10)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt32_t availabilityDuration;
  SE_UInt32_t maxChargeDuration;
  SE_TimeType_t readingTime;
  SE_PerCent_t reserveChargePercent;
  SE_PerCent_t reservePercent;
  SE_ReactivePower_t statVarAvail;
  SE_ActivePower_t statWAvail;
} SE_DERAvailability_t;

typedef struct {
  SE_PowerOfTenMultiplierType_t multiplier;
  SE_UInt16_t value;
} SE_VoltageRMS_t;

// #define SE_subscribable_exists (1 << 1)
#define SE_setVRefOfs_exists (1 << 5)
#define SE_setVRef_exists (1 << 6)
#define SE_setMinPFNeg_exists (1 << 7)
#define SE_setMinPF_exists (1 << 8)
#define SE_setMaxWh_exists (1 << 9)
#define SE_setMaxVarNeg_exists (1 << 10)
#define SE_setMaxVar_exists (1 << 11)
#define SE_setMaxVA_exists (1 << 12)
#define SE_setMaxDischargeRateW_exists (1 << 13)
#define SE_setMaxDischargeRateVA_exists (1 << 14)
#define SE_setMaxChargeRateW_exists (1 << 15)
#define SE_setMaxChargeRateVA_exists (1 << 16)
#define SE_setMaxAh_exists (1 << 17)
#define SE_setMaxA_exists (1 << 18)
#define SE_modesEnabled_exists (1 << 19)
#define SE_setESDelay_exists (1 << 20)
#define SE_setESHighFreq_exists (1 << 21)
#define SE_setESHighVolt_exists (1 << 22)
#define SE_setESLowFreq_exists (1 << 23)
#define SE_setESLowVolt_exists (1 << 24)
#define SE_setESRandomDelay_exists (1 << 25)
#define SE_setSoftGradW_exists (1 << 26)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_DERControlType_t modesEnabled;
  SE_UInt16_t setESDelay;
  SE_UInt16_t setESHighFreq;
  SE_Int16_t setESHighVolt;
  SE_UInt16_t setESLowFreq;
  SE_Int16_t setESLowVolt;
  SE_UInt16_t setESRandomDelay;
  SE_UInt16_t setGradW;
  SE_CurrentRMS_t setMaxA;
  SE_AmpereHour_t setMaxAh;
  SE_ApparentPower_t setMaxChargeRateVA;
  SE_ActivePower_t setMaxChargeRateW;
  SE_ApparentPower_t setMaxDischargeRateVA;
  SE_ActivePower_t setMaxDischargeRateW;
  SE_ApparentPower_t setMaxVA;
  SE_ReactivePower_t setMaxVar;
  SE_ReactivePower_t setMaxVarNeg;
  SE_ActivePower_t setMaxW;
  SE_WattHour_t setMaxWh;
  SE_PowerFactor_t setMinPF;
  SE_PowerFactor_t setMinPFNeg;
  SE_UInt16_t setSoftGradW;
  SE_VoltageRMS_t setVRef;
  SE_VoltageRMS_t setVRefOfs;
  SE_TimeType_t updatedTime;
} SE_DERSettings_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_DERStatusLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_DERSettingsLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_DERCapabilityLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_DERAvailabilityLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_CurrentDERProgramLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_AssociatedUsagePointLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_AssociatedDERProgramListLink_t;

// #define SE_subscribable_exists (1 << 1)
#define SE_DERStatusLink_exists (1 << 5)
#define SE_DERSettingsLink_exists (1 << 6)
#define SE_DERCapabilityLink_exists (1 << 7)
#define SE_DERAvailabilityLink_exists (1 << 8)
#define SE_CurrentDERProgramLink_exists (1 << 9)
#define SE_AssociatedUsagePointLink_exists (1 << 10)
#define SE_AssociatedDERProgramListLink_exists (1 << 11)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_AssociatedDERProgramListLink_t AssociatedDERProgramListLink;
  SE_AssociatedUsagePointLink_t AssociatedUsagePointLink;
  SE_CurrentDERProgramLink_t CurrentDERProgramLink;
  SE_DERAvailabilityLink_t DERAvailabilityLink;
  SE_DERCapabilityLink_t DERCapabilityLink;
  SE_DERSettingsLink_t DERSettingsLink;
  SE_DERStatusLink_t DERStatusLink;
} SE_DER_t;

// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *DER;
} SE_DERList_t;

// #define SE_description_exists (1 << 0)
// #define SE_subscribable_exists (1 << 1)
// #define SE_version_exists (1 << 2)
#define SE_setGradW_exists (1 << 5)
// #define SE_setESDelay_exists (1 << 20)
// #define SE_setESHighFreq_exists (1 << 21)
// #define SE_setESHighVolt_exists (1 << 22)
// #define SE_setESLowFreq_exists (1 << 23)
// #define SE_setESLowVolt_exists (1 << 24)
// #define SE_setESRandomDelay_exists (1 << 25)
// #define SE_setSoftGradW_exists (1 << 26)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_DERControlBase_t DERControlBase;
  SE_UInt16_t setESDelay;
  SE_UInt16_t setESHighFreq;
  SE_Int16_t setESHighVolt;
  SE_UInt16_t setESLowFreq;
  SE_Int16_t setESLowVolt;
  SE_UInt16_t setESRandomDelay;
  SE_UInt16_t setGradW;
  SE_UInt16_t setSoftGradW;
} SE_DefaultDERControl_t;

typedef struct {
  SE_PowerOfTenMultiplierType_t multiplier;
  SE_Int48_t value;
} SE_SignedRealEnergy_t;

// #define SE_description_exists (1 << 0)
// #define SE_subscribable_exists (1 << 1)
// #define SE_version_exists (1 << 2)
// #define SE_responseRequired_exists (1 << 5)
typedef struct {
  uint32_t _flags;
  char * href;
  char * replyTo;
  SE_HexBinary8_t responseRequired;
  SE_SubscribableType_t subscribable;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_TimeType_t creationTime;
  SE_EventStatus_t EventStatus;
  SE_DateTimeInterval_t interval;
  SE_SignedRealEnergy_t energyAvailable;
  SE_ActivePower_t powerAvailable;
  SE_mRIDType_t subject;
} SE_FlowReservationResponse_t;

// #define SE_subscribable_exists (1 << 1)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *FlowReservationResponse;
} SE_FlowReservationResponseList_t;

typedef struct {
  SE_TimeType_t dateTime;
  SE_UInt8_t requestStatus;
} SE_RequestStatus_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_durationRequested_exists (1 << 5)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_TimeType_t creationTime;
  SE_UInt16_t durationRequested;
  SE_SignedRealEnergy_t energyRequested;
  SE_DateTimeInterval_t intervalRequested;
  SE_ActivePower_t powerRequested;
  SE_RequestStatus_t RequestStatus;
} SE_FlowReservationRequest_t;

// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *FlowReservationRequest;
} SE_FlowReservationRequestList_t;

// #define SE_description_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_String32_t description;
  SE_DateTimeInterval_t interval;
} SE_SupplyInterruptionOverride_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *SupplyInterruptionOverride;
} SE_SupplyInterruptionOverrideList_t;

typedef SE_UInt8_t SE_ServiceStatusType_t;

typedef struct {
  SE_ServiceStatusType_t newStatus;
  SE_TimeType_t startTime;
} SE_ServiceChange_t;

typedef SE_UInt8_t SE_CreditTypeType_t;

typedef struct {
  SE_CreditTypeType_t newType;
  SE_TimeType_t startTime;
} SE_CreditTypeChange_t;

#define SE_serviceChange_exists (1 << 5)
#define SE_creditTypeInUse_exists (1 << 6)
#define SE_creditTypeChange_exists (1 << 7)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_CreditTypeChange_t creditTypeChange;
  SE_CreditTypeType_t creditTypeInUse;
  SE_ServiceChange_t serviceChange;
  SE_ServiceStatusType_t serviceStatus;
} SE_PrepayOperationStatus_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_UsagePointLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_MeterReadingListLink_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_MeterReadingListLink_exists (1 << 5)
#define SE_deviceLFDI_exists (1 << 6)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_RoleFlagsType_t roleFlags;
  SE_ServiceKind_t serviceCategoryKind;
  SE_UInt8_t status;
  SE_HexBinary160_t deviceLFDI;
  SE_MeterReadingListLink_t MeterReadingListLink;
} SE_UsagePoint_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_SupplyInterruptionOverrideListLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_PrepayOperationStatusLink_t;

typedef SE_UInt8_t SE_PrepayModeType_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_CreditRegisterListLink_t;

typedef SE_UInt16_t SE_CurrencyCode_t;

typedef struct {
  SE_PowerOfTenMultiplierType_t multiplier;
  SE_UInt48_t value;
} SE_RealEnergy_t;

#define SE_energyUnit_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  SE_RealEnergy_t energyUnit;
  SE_CurrencyCode_t monetaryUnit;
  SE_PowerOfTenMultiplierType_t multiplier;
  SE_Int32_t value;
} SE_AccountingUnit_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ActiveSupplyInterruptionOverrideListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ActiveCreditRegisterListLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_AccountBalanceLink_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_lowEmergencyCreditWarningLevel_exists (1 << 5)
#define SE_lowCreditWarningLevel_exists (1 << 6)
#define SE_creditExpiryLevel_exists (1 << 7)
#define SE_ActiveSupplyInterruptionOverrideListLink_exists (1 << 8)
#define SE_ActiveCreditRegisterListLink_exists (1 << 9)
#define SE_UsagePointLink_exists (1 << 16)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_AccountBalanceLink_t AccountBalanceLink;
  SE_ActiveCreditRegisterListLink_t ActiveCreditRegisterListLink;
  SE_ActiveSupplyInterruptionOverrideListLink_t ActiveSupplyInterruptionOverrideListLink;
  SE_AccountingUnit_t creditExpiryLevel;
  SE_CreditRegisterListLink_t CreditRegisterListLink;
  SE_AccountingUnit_t lowCreditWarningLevel;
  SE_AccountingUnit_t lowEmergencyCreditWarningLevel;
  SE_PrepayModeType_t prepayMode;
  SE_PrepayOperationStatusLink_t PrepayOperationStatusLink;
  SE_SupplyInterruptionOverrideListLink_t SupplyInterruptionOverrideListLink;
  List *UsagePoint;
  SE_UsagePointLink_t UsagePointLink;
} SE_Prepayment_t;

// #define SE_subscribable_exists (1 << 1)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *Prepayment;
} SE_PrepaymentList_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_creditType_exists (1 << 5)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_AccountingUnit_t creditAmount;
  SE_CreditTypeType_t creditType;
  SE_TimeType_t effectiveTime;
  SE_String32_t token;
} SE_CreditRegister_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *CreditRegister;
} SE_CreditRegisterList_t;

typedef SE_UInt8_t SE_CreditStatusType_t;

#define SE_emergencyCreditStatus_exists (1 << 5)
#define SE_emergencyCredit_exists (1 << 6)
#define SE_creditStatus_exists (1 << 7)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_AccountingUnit_t availableCredit;
  SE_CreditStatusType_t creditStatus;
  SE_AccountingUnit_t emergencyCredit;
  SE_CreditStatusType_t emergencyCreditStatus;
} SE_AccountBalance_t;

typedef char SE_String42_t[42];
typedef char SE_String20_t[20];

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_web_exists (1 << 5)
#define SE_providerID_exists (1 << 6)
#define SE_phone_exists (1 << 7)
#define SE_email_exists (1 << 8)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_String32_t email;
  SE_String20_t phone;
  SE_UInt32_t providerID;
  SE_String42_t web;
} SE_ServiceSupplier_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *ServiceSupplier;
} SE_ServiceSupplierList_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_ReadingTypeLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_BillingReadingSetListLink_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_ReadingTypeLink_exists (1 << 5)
#define SE_BillingReadingSetListLink_exists (1 << 6)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_BillingReadingSetListLink_t BillingReadingSetListLink;
  SE_ReadingTypeLink_t ReadingTypeLink;
} SE_BillingMeterReadingBase_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
// #define SE_ReadingTypeLink_exists (1 << 5)
// #define SE_BillingReadingSetListLink_exists (1 << 6)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_BillingReadingSetListLink_t BillingReadingSetListLink;
  SE_ReadingTypeLink_t ReadingTypeLink;
} SE_TargetReading_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *TargetReading;
} SE_TargetReadingList_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
// #define SE_ReadingTypeLink_exists (1 << 5)
// #define SE_BillingReadingSetListLink_exists (1 << 6)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_BillingReadingSetListLink_t BillingReadingSetListLink;
  SE_ReadingTypeLink_t ReadingTypeLink;
} SE_ProjectionReading_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *ProjectionReading;
} SE_ProjectionReadingList_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
// #define SE_ReadingTypeLink_exists (1 << 5)
// #define SE_BillingReadingSetListLink_exists (1 << 6)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_BillingReadingSetListLink_t BillingReadingSetListLink;
  SE_ReadingTypeLink_t ReadingTypeLink;
} SE_HistoricalReading_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *HistoricalReading;
} SE_HistoricalReadingList_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_TariffProfileLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_TargetReadingListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ProjectionReadingListLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_PrepaymentLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_HistoricalReadingListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_BillingPeriodListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ActiveTargetReadingListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ActiveProjectionReadingListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ActiveBillingPeriodListLink_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_TariffProfileLink_exists (1 << 5)
#define SE_TargetReadingListLink_exists (1 << 6)
#define SE_serviceLocation_exists (1 << 7)
#define SE_serviceAccount_exists (1 << 8)
#define SE_ProjectionReadingListLink_exists (1 << 9)
#define SE_PrepaymentLink_exists (1 << 10)
#define SE_HistoricalReadingListLink_exists (1 << 11)
#define SE_BillingPeriodListLink_exists (1 << 12)
#define SE_ActiveTargetReadingListLink_exists (1 << 13)
#define SE_ActiveProjectionReadingListLink_exists (1 << 14)
#define SE_ActiveBillingPeriodListLink_exists (1 << 15)
// #define SE_UsagePointLink_exists (1 << 16)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_ActiveBillingPeriodListLink_t ActiveBillingPeriodListLink;
  SE_ActiveProjectionReadingListLink_t ActiveProjectionReadingListLink;
  SE_ActiveTargetReadingListLink_t ActiveTargetReadingListLink;
  SE_BillingPeriodListLink_t BillingPeriodListLink;
  SE_HistoricalReadingListLink_t HistoricalReadingListLink;
  SE_PrepaymentLink_t PrepaymentLink;
  SE_ProjectionReadingListLink_t ProjectionReadingListLink;
  SE_String42_t serviceAccount;
  SE_String42_t serviceLocation;
  SE_TargetReadingListLink_t TargetReadingListLink;
  SE_TariffProfileLink_t TariffProfileLink;
  SE_UsagePointLink_t UsagePointLink;
} SE_CustomerAgreement_t;

// #define SE_subscribable_exists (1 << 1)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *CustomerAgreement;
} SE_CustomerAgreementList_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_ServiceSupplierLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_CustomerAgreementListLink_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_ServiceSupplierLink_exists (1 << 5)
#define SE_customerName_exists (1 << 6)
#define SE_CustomerAgreementListLink_exists (1 << 7)
#define SE_customerAccount_exists (1 << 8)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_UInt16_t currency;
  SE_String42_t customerAccount;
  SE_CustomerAgreementListLink_t CustomerAgreementListLink;
  SE_String42_t customerName;
  SE_PowerOfTenMultiplierType_t pricePowerOfTenMultiplier;
  SE_ServiceSupplierLink_t ServiceSupplierLink;
} SE_CustomerAccount_t;

// #define SE_subscribable_exists (1 << 1)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *CustomerAccount;
} SE_CustomerAccountList_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_BillingReadingListLink_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_BillingReadingListLink_exists (1 << 5)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_DateTimeInterval_t timePeriod;
  SE_BillingReadingListLink_t BillingReadingListLink;
} SE_BillingReadingSet_t;

// #define SE_subscribable_exists (1 << 1)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *BillingReadingSet;
} SE_BillingReadingSetList_t;

typedef SE_UInt8_t SE_ChargeKind_t;

// #define SE_description_exists (1 << 0)
// #define SE_kind_exists (1 << 22)
typedef struct {
  uint32_t _flags;
  SE_String20_t description;
  SE_ChargeKind_t kind;
  SE_Int32_t value;
} SE_Charge_t;

// #define SE_value_exists (1 << 5)
// #define SE_touTier_exists (1 << 6)
// #define SE_timePeriod_exists (1 << 7)
// #define SE_qualityFlags_exists (1 << 8)
// #define SE_consumptionBlock_exists (1 << 9)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_ConsumptionBlockType_t consumptionBlock;
  SE_HexBinary16_t qualityFlags;
  SE_DateTimeInterval_t timePeriod;
  SE_TOUType_t touTier;
  SE_Int48_t value;
  List *Charge;
} SE_BillingReading_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *BillingReading;
} SE_BillingReadingList_t;

#define SE_statusTimeStamp_exists (1 << 5)
#define SE_billToDate_exists (1 << 6)
#define SE_billLastPeriod_exists (1 << 7)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_Int48_t billLastPeriod;
  SE_Int48_t billToDate;
  SE_DateTimeInterval_t interval;
  SE_TimeType_t statusTimeStamp;
} SE_BillingPeriod_t;

// #define SE_subscribable_exists (1 << 1)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *BillingPeriod;
} SE_BillingPeriodList_t;

typedef SE_UInt8_t SE_PriorityType_t;

// #define SE_description_exists (1 << 0)
// #define SE_subscribable_exists (1 << 1)
// #define SE_version_exists (1 << 2)
// #define SE_responseRequired_exists (1 << 5)
#define SE_originator_exists (1 << 6)
typedef struct {
  uint32_t _flags;
  char * href;
  char * replyTo;
  SE_HexBinary8_t responseRequired;
  SE_SubscribableType_t subscribable;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_TimeType_t creationTime;
  SE_EventStatus_t EventStatus;
  SE_DateTimeInterval_t interval;
  SE_String20_t originator;
  SE_PriorityType_t priority;
  char * textMessage;
} SE_TextMessage_t;

// #define SE_subscribable_exists (1 << 1)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *TextMessage;
} SE_TextMessageList_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_TextMessageListLink_t;

typedef SE_String42_t SE_LocaleType_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ActiveTextMessageListLink_t;

// #define SE_description_exists (1 << 0)
// #define SE_subscribable_exists (1 << 1)
// #define SE_version_exists (1 << 2)
#define SE_TextMessageListLink_exists (1 << 5)
#define SE_ActiveTextMessageListLink_exists (1 << 6)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_ActiveTextMessageListLink_t ActiveTextMessageListLink;
  SE_LocaleType_t locale;
  SE_PrimacyType_t primacy;
  SE_TextMessageListLink_t TextMessageListLink;
} SE_MessagingProgram_t;

// #define SE_subscribable_exists (1 << 1)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *MessagingProgram;
} SE_MessagingProgramList_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ConsumptionTariffIntervalListLink_t;

// #define SE_description_exists (1 << 0)
// #define SE_subscribable_exists (1 << 1)
// #define SE_version_exists (1 << 2)
// #define SE_responseRequired_exists (1 << 5)
// #define SE_randomizeStart_exists (1 << 6)
// #define SE_randomizeDuration_exists (1 << 7)
#define SE_ConsumptionTariffIntervalListLink_exists (1 << 8)
typedef struct {
  uint32_t _flags;
  char * href;
  char * replyTo;
  SE_HexBinary8_t responseRequired;
  SE_SubscribableType_t subscribable;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_TimeType_t creationTime;
  SE_EventStatus_t EventStatus;
  SE_DateTimeInterval_t interval;
  SE_OneHourRangeType_t randomizeDuration;
  SE_OneHourRangeType_t randomizeStart;
  SE_ConsumptionTariffIntervalListLink_t ConsumptionTariffIntervalListLink;
  SE_TOUType_t touTier;
} SE_TimeTariffInterval_t;

// #define SE_subscribable_exists (1 << 1)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *TimeTariffInterval;
} SE_TimeTariffIntervalList_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_RateComponentListLink_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_rateCode_exists (1 << 5)
#define SE_pricePowerOfTenMultiplier_exists (1 << 6)
#define SE_currency_exists (1 << 7)
#define SE_RateComponentListLink_exists (1 << 8)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_CurrencyCode_t currency;
  SE_PowerOfTenMultiplierType_t pricePowerOfTenMultiplier;
  SE_PrimacyType_t primacy;
  SE_String20_t rateCode;
  SE_RateComponentListLink_t RateComponentListLink;
  SE_ServiceKind_t serviceCategoryKind;
} SE_TariffProfile_t;

// #define SE_subscribable_exists (1 << 1)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *TariffProfile;
} SE_TariffProfileList_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_TimeTariffIntervalListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ActiveTimeTariffIntervalListLink_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_flowRateStartLimit_exists (1 << 5)
#define SE_flowRateEndLimit_exists (1 << 6)
#define SE_ActiveTimeTariffIntervalListLink_exists (1 << 7)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_ActiveTimeTariffIntervalListLink_t ActiveTimeTariffIntervalListLink;
  SE_UnitValueType_t flowRateEndLimit;
  SE_UnitValueType_t flowRateStartLimit;
  SE_ReadingTypeLink_t ReadingTypeLink;
  SE_RoleFlagsType_t roleFlags;
  SE_TimeTariffIntervalListLink_t TimeTariffIntervalListLink;
} SE_RateComponent_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *RateComponent;
} SE_RateComponentList_t;

typedef SE_UInt8_t SE_CostKindType_t;

typedef struct {
  SE_UInt32_t amount;
  SE_CostKindType_t costKind;
  SE_UInt8_t costLevel;
  SE_UInt8_t numCostLevels;
} SE_EnvironmentalCost_t;

#define SE_price_exists (1 << 5)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_ConsumptionBlockType_t consumptionBlock;
  List *EnvironmentalCost;
  SE_Int32_t price;
  SE_UInt48_t startValue;
} SE_ConsumptionTariffInterval_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *ConsumptionTariffInterval;
} SE_ConsumptionTariffIntervalList_t;

// #define SE_subscribable_exists (1 << 1)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *UsagePoint;
} SE_UsagePointList_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ReadingListLink_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_ReadingListLink_exists (1 << 5)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_DateTimeInterval_t timePeriod;
  SE_ReadingListLink_t ReadingListLink;
} SE_ReadingSet_t;

// #define SE_subscribable_exists (1 << 1)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *ReadingSet;
} SE_ReadingSetList_t;

// #define SE_subscribable_exists (1 << 1)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *Reading;
} SE_ReadingList_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ReadingSetListLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_ReadingLink_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_ReadingSetListLink_exists (1 << 5)
#define SE_ReadingLink_exists (1 << 6)
// #define SE_RateComponentListLink_exists (1 << 8)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_RateComponentListLink_t RateComponentListLink;
  SE_ReadingLink_t ReadingLink;
  SE_ReadingSetListLink_t ReadingSetListLink;
  SE_ReadingTypeLink_t ReadingTypeLink;
} SE_MeterReading_t;

// #define SE_subscribable_exists (1 << 1)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *MeterReading;
} SE_MeterReadingList_t;

typedef SE_UInt8_t SE_UnitType_t;

typedef struct {
  SE_UnitType_t type;
  SE_UInt16_t value;
} SE_TargetReduction_t;

#define SE_heatingSetpoint_exists (1 << 0)
#define SE_coolingSetpoint_exists (1 << 1)
typedef struct {
  uint32_t _flags;
  SE_Int16_t coolingSetpoint;
  SE_Int16_t heatingSetpoint;
} SE_SetPoint_t;

#define SE_loadAdjustmentPercentageOffset_exists (1 << 0)
#define SE_heatingOffset_exists (1 << 1)
#define SE_coolingOffset_exists (1 << 2)
typedef struct {
  uint32_t _flags;
  SE_UInt8_t coolingOffset;
  SE_UInt8_t heatingOffset;
  SE_PerCent_t loadAdjustmentPercentageOffset;
} SE_Offset_t;

typedef struct {
  SE_UInt8_t normalValue;
} SE_DutyCycle_t;

typedef SE_HexBinary32_t SE_DeviceCategoryType_t;
typedef SE_UInt8_t SE_ApplianceLoadReductionType_t;

typedef struct {
  SE_ApplianceLoadReductionType_t type;
} SE_ApplianceLoadReduction_t;

// #define SE_description_exists (1 << 0)
// #define SE_subscribable_exists (1 << 1)
// #define SE_version_exists (1 << 2)
// #define SE_responseRequired_exists (1 << 5)
// #define SE_randomizeStart_exists (1 << 6)
// #define SE_randomizeDuration_exists (1 << 7)
#define SE_TargetReduction_exists (1 << 8)
#define SE_loadShiftForward_true (1 << 9)
#define SE_drProgramMandatory_true (1 << 10)
#define SE_ApplianceLoadReduction_exists (1 << 11)
#define SE_DutyCycle_exists (1 << 12)
#define SE_Offset_exists (1 << 13)
#define SE_overrideDuration_exists (1 << 14)
#define SE_SetPoint_exists (1 << 15)
typedef struct {
  uint32_t _flags;
  char * href;
  char * replyTo;
  SE_HexBinary8_t responseRequired;
  SE_SubscribableType_t subscribable;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_TimeType_t creationTime;
  SE_EventStatus_t EventStatus;
  SE_DateTimeInterval_t interval;
  SE_OneHourRangeType_t randomizeDuration;
  SE_OneHourRangeType_t randomizeStart;
  SE_ApplianceLoadReduction_t ApplianceLoadReduction;
  SE_DeviceCategoryType_t deviceCategory;
  SE_DutyCycle_t DutyCycle;
  SE_Offset_t Offset;
  SE_UInt16_t overrideDuration;
  SE_SetPoint_t SetPoint;
  SE_TargetReduction_t TargetReduction;
} SE_EndDeviceControl_t;

// #define SE_subscribable_exists (1 << 1)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *EndDeviceControl;
} SE_EndDeviceControlList_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_EndDeviceControlListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ActiveEndDeviceControlListLink_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_EndDeviceControlListLink_exists (1 << 5)
#define SE_availabilityUpdatePowerChangeThreshold_exists (1 << 6)
#define SE_availabilityUpdatePercentChangeThreshold_exists (1 << 7)
#define SE_ActiveEndDeviceControlListLink_exists (1 << 8)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_ActiveEndDeviceControlListLink_t ActiveEndDeviceControlListLink;
  SE_PerCent_t availabilityUpdatePercentChangeThreshold;
  SE_ActivePower_t availabilityUpdatePowerChangeThreshold;
  SE_EndDeviceControlListLink_t EndDeviceControlListLink;
  SE_PrimacyType_t primacy;
} SE_DemandResponseProgram_t;

// #define SE_subscribable_exists (1 << 1)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *DemandResponseProgram;
} SE_DemandResponseProgramList_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_DemandResponseProgramLink_t;

#define SE_sheddablePower_exists (1 << 5)
#define SE_sheddablePercent_exists (1 << 6)
#define SE_DemandResponseProgramLink_exists (1 << 7)
// #define SE_availabilityDuration_exists (1 << 10)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt32_t availabilityDuration;
  SE_DemandResponseProgramLink_t DemandResponseProgramLink;
  SE_PerCent_t sheddablePercent;
  SE_ActivePower_t sheddablePower;
} SE_LoadShedAvailability_t;

// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *LoadShedAvailability;
} SE_LoadShedAvailabilityList_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_FileLink_t;

#define SE_FileLink_exists (1 << 5)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt32_t pollRate;
  SE_TimeType_t activateTime;
  SE_FileLink_t FileLink;
  SE_UInt8_t loadPercent;
  SE_TimeType_t nextRequestAttempt;
  SE_UInt16_t request503Count;
  SE_UInt16_t requestFailCount;
  SE_UInt8_t status;
  SE_TimeType_t statusTime;
} SE_FileStatus_t;

typedef char SE_String16_t[16];
typedef SE_UInt32_t SE_PENType_t;

// #define SE_lFDI_exists (1 << 3)
#define SE_mfSerNum_exists (1 << 5)
#define SE_mfHwVer_exists (1 << 6)
#define SE_activateTime_exists (1 << 7)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_TimeType_t activateTime;
  char * fileURI;
  SE_HexBinary160_t lFDI;
  SE_String32_t mfHwVer;
  SE_PENType_t mfID;
  SE_String32_t mfModel;
  SE_String32_t mfSerNum;
  SE_String16_t mfVer;
  SE_UInt32_t size;
  SE_HexBinary16_t type;
} SE_File_t;

// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *File;
} SE_FileList_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_RateComponentLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_Int32_t consumeThreshold;
  SE_Int32_t maxReductionThreshold;
  SE_RateComponentLink_t RateComponentLink;
} SE_PriceResponseCfg_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *PriceResponseCfg;
} SE_PriceResponseCfgList_t;

typedef SE_Int32_t SE_TimeOffsetType_t;
typedef SE_HexBinary32_t SE_DstRuleType_t;

typedef struct {
  SE_DstRuleType_t dstEndRule;
  SE_TimeOffsetType_t dstOffset;
  SE_DstRuleType_t dstStartRule;
  SE_TimeOffsetType_t tzOffset;
} SE_TimeConfiguration_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_PriceResponseCfgListLink_t;

#define SE_lowChargeThreshold_exists (1 << 0)
#define SE_batteryInstallTime_exists (1 << 1)
typedef struct {
  uint32_t _flags;
  SE_TimeType_t batteryInstallTime;
  SE_UInt32_t lowChargeThreshold;
} SE_PowerConfiguration_t;

// #define SE_subscribable_exists (1 << 1)
#define SE_TimeConfiguration_exists (1 << 5)
#define SE_PriceResponseCfgListLink_exists (1 << 6)
#define SE_PowerConfiguration_exists (1 << 7)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt32_t pollRate;
  SE_LocaleType_t currentLocale;
  SE_PowerConfiguration_t PowerConfiguration;
  SE_PriceResponseCfgListLink_t PriceResponseCfgListLink;
  SE_TimeConfiguration_t TimeConfiguration;
  SE_String32_t userDeviceName;
} SE_Configuration_t;

#define SE_extendedData_exists (1 << 5)
#define SE_details_exists (1 << 6)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_TimeType_t createdDateTime;
  SE_String32_t details;
  SE_UInt32_t extendedData;
  SE_UInt8_t functionSet;
  SE_UInt8_t logEventCode;
  SE_UInt16_t logEventID;
  SE_PENType_t logEventPEN;
  SE_UInt8_t profileID;
} SE_LogEvent_t;

// #define SE_subscribable_exists (1 << 1)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *LogEvent;
} SE_LogEventList_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_HexBinary128_t DestAddress;
  SE_HexBinary128_t SourceRoute;
} SE_RPLSourceRoutes_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *RPLSourceRoutes;
} SE_RPLSourceRoutesList_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_RPLSourceRoutesListLink_t;

#define SE_RPLSourceRoutesListLink_exists (1 << 5)
#define SE_groundedFlag_true (1 << 6)
#define SE_DODAGroot_true (1 << 7)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt8_t DODAGid;
  SE_UInt8_t flags;
  SE_UInt8_t MOP;
  SE_UInt8_t PRF;
  SE_UInt16_t rank;
  SE_UInt8_t RPLInstanceID;
  SE_RPLSourceRoutesListLink_t RPLSourceRoutesListLink;
  SE_UInt8_t versionNumber;
} SE_RPLInstance_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *RPLInstance;
} SE_RPLInstanceList_t;

#define SE_isChild_true (1 << 5)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt8_t linkQuality;
  SE_UInt16_t shortAddress;
} SE_Neighbor_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *Neighbor;
} SE_NeighborList_t;

#define SE_octetsTx_exists (1 << 0)
#define SE_octetsRx_exists (1 << 1)
typedef struct {
  uint32_t _flags;
  SE_UInt32_t octetsRx;
  SE_UInt32_t octetsTx;
  SE_UInt32_t packetsRx;
  SE_UInt32_t packetsTx;
  SE_UInt32_t rxFragError;
} SE_loWPAN_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_NeighborListLink_t;

#define SE_NeighborListLink_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  SE_HexBinary8_t capabilityInfo;
  SE_NeighborListLink_t NeighborListLink;
  SE_UInt16_t shortAddress;
} SE_IEEE_802_15_4_t;

typedef uint8_t SE_HexBinary64_t[8];

#define SE_loWPAN_exists (1 << 5)
#define SE_LLSecurityErrorRx_exists (1 << 6)
#define SE_LLRetryCount_exists (1 << 7)
#define SE_LLOctetsTx_exists (1 << 8)
#define SE_LLOctetsRx_exists (1 << 9)
#define SE_LLMediaAccessFail_exists (1 << 10)
#define SE_LLFramesTx_exists (1 << 11)
#define SE_LLFramesRx_exists (1 << 12)
#define SE_LLFramesDropTx_exists (1 << 13)
#define SE_LLFramesDropRx_exists (1 << 14)
#define SE_LLCSMAFail_exists (1 << 15)
#define SE_LLAckNotRx_exists (1 << 16)
#define SE_IEEE_802_15_4_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt32_t CRCerrors;
  SE_HexBinary64_t EUI64;
  SE_IEEE_802_15_4_t IEEE_802_15_4;
  SE_UInt8_t linkLayerType;
  SE_UInt32_t LLAckNotRx;
  SE_UInt32_t LLCSMAFail;
  SE_UInt32_t LLFramesDropRx;
  SE_UInt32_t LLFramesDropTx;
  SE_UInt32_t LLFramesRx;
  SE_UInt32_t LLFramesTx;
  SE_UInt32_t LLMediaAccessFail;
  SE_UInt32_t LLOctetsRx;
  SE_UInt32_t LLOctetsTx;
  SE_UInt32_t LLRetryCount;
  SE_UInt32_t LLSecurityErrorRx;
  SE_loWPAN_t loWPAN;
} SE_LLInterface_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *LLInterface;
} SE_LLInterfaceList_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_LLInterfaceListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_IPAddrListLink_t;

#define SE_LLInterfaceListLink_exists (1 << 5)
#define SE_lastUpdatedTime_exists (1 << 6)
#define SE_lastResetTime_exists (1 << 7)
#define SE_IPAddrListLink_exists (1 << 8)
#define SE_ifType_exists (1 << 9)
#define SE_ifSpeed_exists (1 << 10)
#define SE_ifPromiscuousMode_true (1 << 11)
#define SE_ifPromiscuousMode_exists (1 << 12)
#define SE_ifOutUcastPkts_exists (1 << 13)
#define SE_ifOutOctets_exists (1 << 14)
#define SE_ifOutMulticastPkts_exists (1 << 15)
#define SE_ifOutErrors_exists (1 << 16)
#define SE_ifOutDiscards_exists (1 << 17)
#define SE_ifOutBroadcastPkts_exists (1 << 18)
#define SE_ifOperStatus_exists (1 << 19)
#define SE_ifName_exists (1 << 20)
#define SE_ifMtu_exists (1 << 21)
#define SE_ifInUnknownProtos_exists (1 << 22)
#define SE_ifInUcastPkts_exists (1 << 23)
#define SE_ifInOctets_exists (1 << 24)
#define SE_ifInMulticastPkts_exists (1 << 25)
#define SE_ifInErrors_exists (1 << 26)
#define SE_ifInDiscards_exists (1 << 27)
#define SE_ifIndex_exists (1 << 28)
#define SE_ifInBroadcastPkts_exists (1 << 29)
#define SE_ifHighSpeed_exists (1 << 30)
#define SE_ifDescr_exists (1 << 31)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_String192_t ifDescr;
  SE_UInt32_t ifHighSpeed;
  SE_UInt32_t ifInBroadcastPkts;
  SE_UInt32_t ifIndex;
  SE_UInt32_t ifInDiscards;
  SE_UInt32_t ifInErrors;
  SE_UInt32_t ifInMulticastPkts;
  SE_UInt32_t ifInOctets;
  SE_UInt32_t ifInUcastPkts;
  SE_UInt32_t ifInUnknownProtos;
  SE_UInt32_t ifMtu;
  SE_String16_t ifName;
  SE_UInt8_t ifOperStatus;
  SE_UInt32_t ifOutBroadcastPkts;
  SE_UInt32_t ifOutDiscards;
  SE_UInt32_t ifOutErrors;
  SE_UInt32_t ifOutMulticastPkts;
  SE_UInt32_t ifOutOctets;
  SE_UInt32_t ifOutUcastPkts;
  SE_UInt32_t ifSpeed;
  SE_UInt16_t ifType;
  SE_IPAddrListLink_t IPAddrListLink;
  SE_Int64_t lastResetTime;
  SE_Int64_t lastUpdatedTime;
  SE_LLInterfaceListLink_t LLInterfaceListLink;
} SE_IPInterface_t;

// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *IPInterface;
} SE_IPInterfaceList_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_RPLInstanceListLink_t;

#define SE_RPLInstanceListLink_exists (1 << 5)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_HexBinary128_t address;
  SE_RPLInstanceListLink_t RPLInstanceListLink;
} SE_IPAddr_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *IPAddr;
} SE_IPAddrList_t;

typedef struct {
  SE_ActivePower_t chargingPowerNow;
  SE_RealEnergy_t energyRequestNow;
  SE_ActivePower_t maxForwardPower;
  SE_UInt32_t minimumChargingDuration;
  SE_PerCent_t targetStateOfCharge;
  SE_TimeType_t timeChargeIsNeeded;
  SE_TimeType_t timeChargingStatusPEV;
} SE_PEVInfo_t;

typedef SE_UInt8_t SE_PowerSourceType_t;

#define SE_totalTimeOnBattery_exists (1 << 5)
#define SE_sessionTimeOnBattery_exists (1 << 6)
#define SE_PEVInfo_exists (1 << 7)
#define SE_estimatedTimeRemaining_exists (1 << 8)
#define SE_estimatedChargeRemaining_exists (1 << 9)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt32_t pollRate;
  SE_UInt8_t batteryStatus;
  SE_TimeType_t changedTime;
  SE_PowerSourceType_t currentPowerSource;
  SE_PerCent_t estimatedChargeRemaining;
  SE_UInt32_t estimatedTimeRemaining;
  SE_PEVInfo_t PEVInfo;
  SE_UInt32_t sessionTimeOnBattery;
  SE_UInt32_t totalTimeOnBattery;
} SE_PowerStatus_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_LocaleType_t locale;
} SE_SupportedLocale_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *SupportedLocale;
} SE_SupportedLocaleList_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_SupportedLocaleListLink_t;

typedef struct {
  SE_RealEnergy_t averageEnergy;
  SE_ActivePower_t maxDemand;
  SE_HexBinary32_t optionsImplemented;
} SE_DRLCCapabilities_t;

#define SE_SupportedLocaleListLink_exists (1 << 5)
#define SE_mfInfo_exists (1 << 6)
#define SE_functionsImplemented_exists (1 << 7)
#define SE_DRLCCapabilities_exists (1 << 8)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt32_t pollRate;
  SE_DRLCCapabilities_t DRLCCapabilities;
  SE_HexBinary64_t functionsImplemented;
  SE_HexBinary160_t lFDI;
  SE_TimeType_t mfDate;
  SE_String32_t mfHwVer;
  SE_PENType_t mfID;
  SE_String32_t mfInfo;
  SE_String32_t mfModel;
  SE_String32_t mfSerNum;
  SE_PowerSourceType_t primaryPower;
  SE_PowerSourceType_t secondaryPower;
  SE_SupportedLocaleListLink_t SupportedLocaleListLink;
  SE_TimeType_t swActTime;
  SE_String32_t swVer;
} SE_DeviceInformation_t;

#define SE_localTime_exists (1 << 5)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt32_t pollRate;
  SE_TimeType_t currentTime;
  SE_TimeType_t dstEndTime;
  SE_TimeOffsetType_t dstOffset;
  SE_TimeType_t dstStartTime;
  SE_TimeType_t localTime;
  SE_UInt8_t quality;
  SE_TimeOffsetType_t tzOffset;
} SE_Time_t;

#define SE_status_exists (1 << 5)
#define SE_createdDateTime_exists (1 << 6)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_TimeType_t createdDateTime;
  SE_HexBinary160_t endDeviceLFDI;
  SE_UInt8_t status;
  SE_mRIDType_t subject;
} SE_Response_t;

// #define SE_status_exists (1 << 5)
// #define SE_createdDateTime_exists (1 << 6)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_TimeType_t createdDateTime;
  SE_HexBinary160_t endDeviceLFDI;
  SE_UInt8_t status;
  SE_mRIDType_t subject;
} SE_TextResponse_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ResponseListLink_t;

// #define SE_description_exists (1 << 0)
// #define SE_version_exists (1 << 2)
#define SE_ResponseListLink_exists (1 << 5)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
  SE_ResponseListLink_t ResponseListLink;
} SE_ResponseSet_t;

// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *ResponseSet;
} SE_ResponseSetList_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *Response;
} SE_ResponseList_t;

// #define SE_status_exists (1 << 5)
// #define SE_createdDateTime_exists (1 << 6)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_TimeType_t createdDateTime;
  SE_HexBinary160_t endDeviceLFDI;
  SE_UInt8_t status;
  SE_mRIDType_t subject;
} SE_PriceResponse_t;

typedef struct {
  SE_UnitType_t type;
  SE_UInt16_t value;
} SE_AppliedTargetReduction_t;

// #define SE_status_exists (1 << 5)
// #define SE_createdDateTime_exists (1 << 6)
#define SE_AppliedTargetReduction_exists (1 << 7)
// #define SE_ApplianceLoadReduction_exists (1 << 11)
// #define SE_DutyCycle_exists (1 << 12)
// #define SE_Offset_exists (1 << 13)
// #define SE_overrideDuration_exists (1 << 14)
// #define SE_SetPoint_exists (1 << 15)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_TimeType_t createdDateTime;
  SE_HexBinary160_t endDeviceLFDI;
  SE_UInt8_t status;
  SE_mRIDType_t subject;
  SE_ApplianceLoadReduction_t ApplianceLoadReduction;
  SE_AppliedTargetReduction_t AppliedTargetReduction;
  SE_DutyCycle_t DutyCycle;
  SE_Offset_t Offset;
  SE_UInt16_t overrideDuration;
  SE_SetPoint_t SetPoint;
} SE_DrResponse_t;

// #define SE_status_exists (1 << 5)
// #define SE_createdDateTime_exists (1 << 6)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_TimeType_t createdDateTime;
  SE_HexBinary160_t endDeviceLFDI;
  SE_UInt8_t status;
  SE_mRIDType_t subject;
} SE_FlowReservationResponseResponse_t;

// #define SE_status_exists (1 << 5)
// #define SE_createdDateTime_exists (1 << 6)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_TimeType_t createdDateTime;
  SE_HexBinary160_t endDeviceLFDI;
  SE_UInt8_t status;
  SE_mRIDType_t subject;
} SE_DERControlResponse_t;

typedef struct {
  uint32_t _flags;
  char * href;
  char * subscribedResource;
} SE_SubscriptionBase_t;

#define SE_Resource_exists (1 << 5)
typedef struct {
  uint32_t _flags;
  char * href;
  char * subscribedResource;
  char * newResourceURI;
  SE_Resource_t Resource;
  SE_UInt8_t status;
  char * subscriptionURI;
} SE_Notification_t;

typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  List *Notification;
} SE_NotificationList_t;

typedef struct {
  SE_UInt8_t attributeIdentifier;
  SE_Int48_t lowerThreshold;
  SE_Int48_t upperThreshold;
} SE_Condition_t;

#define SE_Condition_exists (1 << 5)
typedef struct {
  uint32_t _flags;
  char * href;
  char * subscribedResource;
  SE_Condition_t Condition;
  SE_UInt8_t encoding;
  SE_String16_t level;
  SE_UInt16_t limit;
  char * notificationURI;
} SE_Subscription_t;

// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *Subscription;
} SE_SubscriptionList_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_UsagePointListLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_TimeLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_TariffProfileListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_ResponseSetListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_PrepaymentListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_MessagingProgramListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_FileListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_DERProgramListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_DemandResponseProgramListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_CustomerAccountListLink_t;

// #define SE_description_exists (1 << 0)
// #define SE_TimeLink_exists (1 << 4)
#define SE_UsagePointListLink_exists (1 << 5)
#define SE_TariffProfileListLink_exists (1 << 6)
#define SE_ResponseSetListLink_exists (1 << 7)
#define SE_PrepaymentListLink_exists (1 << 8)
#define SE_MessagingProgramListLink_exists (1 << 9)
#define SE_FileListLink_exists (1 << 10)
#define SE_DERProgramListLink_exists (1 << 11)
#define SE_DemandResponseProgramListLink_exists (1 << 12)
#define SE_CustomerAccountListLink_exists (1 << 13)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_CustomerAccountListLink_t CustomerAccountListLink;
  SE_DemandResponseProgramListLink_t DemandResponseProgramListLink;
  SE_DERProgramListLink_t DERProgramListLink;
  SE_FileListLink_t FileListLink;
  SE_MessagingProgramListLink_t MessagingProgramListLink;
  SE_PrepaymentListLink_t PrepaymentListLink;
  SE_ResponseSetListLink_t ResponseSetListLink;
  SE_TariffProfileListLink_t TariffProfileListLink;
  SE_TimeLink_t TimeLink;
  SE_UsagePointListLink_t UsagePointListLink;
} SE_FunctionSetAssignmentsBase_t;

// #define SE_description_exists (1 << 0)
// #define SE_subscribable_exists (1 << 1)
// #define SE_version_exists (1 << 2)
// #define SE_TimeLink_exists (1 << 4)
// #define SE_UsagePointListLink_exists (1 << 5)
// #define SE_TariffProfileListLink_exists (1 << 6)
// #define SE_ResponseSetListLink_exists (1 << 7)
// #define SE_PrepaymentListLink_exists (1 << 8)
// #define SE_MessagingProgramListLink_exists (1 << 9)
// #define SE_FileListLink_exists (1 << 10)
// #define SE_DERProgramListLink_exists (1 << 11)
// #define SE_DemandResponseProgramListLink_exists (1 << 12)
// #define SE_CustomerAccountListLink_exists (1 << 13)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_CustomerAccountListLink_t CustomerAccountListLink;
  SE_DemandResponseProgramListLink_t DemandResponseProgramListLink;
  SE_DERProgramListLink_t DERProgramListLink;
  SE_FileListLink_t FileListLink;
  SE_MessagingProgramListLink_t MessagingProgramListLink;
  SE_PrepaymentListLink_t PrepaymentListLink;
  SE_ResponseSetListLink_t ResponseSetListLink;
  SE_TariffProfileListLink_t TariffProfileListLink;
  SE_TimeLink_t TimeLink;
  SE_UsagePointListLink_t UsagePointListLink;
  SE_SubscribableType_t subscribable;
  SE_mRIDType_t mRID;
  SE_String32_t description;
  SE_VersionType_t version;
} SE_FunctionSetAssignments_t;

// #define SE_subscribable_exists (1 << 1)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *FunctionSetAssignments;
} SE_FunctionSetAssignmentsList_t;

typedef uint64_t SE_UInt40_t;
typedef SE_UInt40_t SE_SFDIType_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_PowerStatusLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_LogEventListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_LoadShedAvailabilityListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_IPInterfaceListLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_FileStatusLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_DeviceStatusLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_DeviceInformationLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_DERListLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_ConfigurationLink_t;

// #define SE_subscribable_exists (1 << 1)
// #define SE_lFDI_exists (1 << 3)
#define SE_PowerStatusLink_exists (1 << 5)
#define SE_LogEventListLink_exists (1 << 6)
#define SE_loadShedDeviceCategory_exists (1 << 7)
#define SE_LoadShedAvailabilityListLink_exists (1 << 8)
#define SE_IPInterfaceListLink_exists (1 << 9)
#define SE_FileStatusLink_exists (1 << 10)
#define SE_DeviceStatusLink_exists (1 << 11)
#define SE_DeviceInformationLink_exists (1 << 12)
#define SE_DERListLink_exists (1 << 13)
#define SE_ConfigurationLink_exists (1 << 14)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_ConfigurationLink_t ConfigurationLink;
  SE_DERListLink_t DERListLink;
  SE_DeviceInformationLink_t DeviceInformationLink;
  SE_DeviceStatusLink_t DeviceStatusLink;
  SE_FileStatusLink_t FileStatusLink;
  SE_IPInterfaceListLink_t IPInterfaceListLink;
  SE_HexBinary160_t lFDI;
  SE_LoadShedAvailabilityListLink_t LoadShedAvailabilityListLink;
  SE_DeviceCategoryType_t loadShedDeviceCategory;
  SE_LogEventListLink_t LogEventListLink;
  SE_PowerStatusLink_t PowerStatusLink;
  SE_SFDIType_t sFDI;
} SE_AbstractDevice_t;

// #define SE_subscribable_exists (1 << 1)
// #define SE_lFDI_exists (1 << 3)
// #define SE_PowerStatusLink_exists (1 << 5)
// #define SE_LogEventListLink_exists (1 << 6)
// #define SE_loadShedDeviceCategory_exists (1 << 7)
// #define SE_LoadShedAvailabilityListLink_exists (1 << 8)
// #define SE_IPInterfaceListLink_exists (1 << 9)
// #define SE_FileStatusLink_exists (1 << 10)
// #define SE_DeviceStatusLink_exists (1 << 11)
// #define SE_DeviceInformationLink_exists (1 << 12)
// #define SE_DERListLink_exists (1 << 13)
// #define SE_ConfigurationLink_exists (1 << 14)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_ConfigurationLink_t ConfigurationLink;
  SE_DERListLink_t DERListLink;
  SE_DeviceInformationLink_t DeviceInformationLink;
  SE_DeviceStatusLink_t DeviceStatusLink;
  SE_FileStatusLink_t FileStatusLink;
  SE_IPInterfaceListLink_t IPInterfaceListLink;
  SE_HexBinary160_t lFDI;
  SE_LoadShedAvailabilityListLink_t LoadShedAvailabilityListLink;
  SE_DeviceCategoryType_t loadShedDeviceCategory;
  SE_LogEventListLink_t LogEventListLink;
  SE_PowerStatusLink_t PowerStatusLink;
  SE_SFDIType_t sFDI;
  SE_UInt32_t pollRate;
} SE_SelfDevice_t;

typedef SE_UInt32_t SE_PINType_t;

// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt32_t pollRate;
  SE_TimeType_t dateTimeRegistered;
  SE_PINType_t pIN;
} SE_Registration_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_SubscriptionListLink_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_RegistrationLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_FunctionSetAssignmentsListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_FlowReservationResponseListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_FlowReservationRequestListLink_t;

// #define SE_subscribable_exists (1 << 1)
// #define SE_lFDI_exists (1 << 3)
// #define SE_PowerStatusLink_exists (1 << 5)
// #define SE_LogEventListLink_exists (1 << 6)
// #define SE_loadShedDeviceCategory_exists (1 << 7)
// #define SE_LoadShedAvailabilityListLink_exists (1 << 8)
// #define SE_IPInterfaceListLink_exists (1 << 9)
// #define SE_FileStatusLink_exists (1 << 10)
// #define SE_DeviceStatusLink_exists (1 << 11)
// #define SE_DeviceInformationLink_exists (1 << 12)
// #define SE_DERListLink_exists (1 << 13)
// #define SE_ConfigurationLink_exists (1 << 14)
#define SE_SubscriptionListLink_exists (1 << 15)
#define SE_RegistrationLink_exists (1 << 16)
#define SE_FunctionSetAssignmentsListLink_exists (1 << 17)
#define SE_FlowReservationResponseListLink_exists (1 << 18)
#define SE_FlowReservationRequestListLink_exists (1 << 19)
#define SE_enabled_true (1 << 20)
#define SE_enabled_exists (1 << 21)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_ConfigurationLink_t ConfigurationLink;
  SE_DERListLink_t DERListLink;
  SE_DeviceInformationLink_t DeviceInformationLink;
  SE_DeviceStatusLink_t DeviceStatusLink;
  SE_FileStatusLink_t FileStatusLink;
  SE_IPInterfaceListLink_t IPInterfaceListLink;
  SE_HexBinary160_t lFDI;
  SE_LoadShedAvailabilityListLink_t LoadShedAvailabilityListLink;
  SE_DeviceCategoryType_t loadShedDeviceCategory;
  SE_LogEventListLink_t LogEventListLink;
  SE_PowerStatusLink_t PowerStatusLink;
  SE_SFDIType_t sFDI;
  SE_TimeType_t changedTime;
  SE_FlowReservationRequestListLink_t FlowReservationRequestListLink;
  SE_FlowReservationResponseListLink_t FlowReservationResponseListLink;
  SE_FunctionSetAssignmentsListLink_t FunctionSetAssignmentsListLink;
  SE_RegistrationLink_t RegistrationLink;
  SE_SubscriptionListLink_t SubscriptionListLink;
} SE_EndDevice_t;

// #define SE_subscribable_exists (1 << 1)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_SubscribableType_t subscribable;
  SE_UInt16_t all;
  SE_UInt8_t results;
  SE_UInt32_t pollRate;
  List *EndDevice;
} SE_EndDeviceList_t;

typedef struct {
  SE_PowerOfTenMultiplierType_t multiplier;
  SE_UInt8_t subject;
  SE_Int16_t value;
} SE_Temperature_t;

// #define SE_TimeLink_exists (1 << 4)
#define SE_opTime_exists (1 << 5)
#define SE_opState_exists (1 << 6)
#define SE_onCount_exists (1 << 7)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt32_t pollRate;
  SE_TimeType_t changedTime;
  SE_UInt16_t onCount;
  SE_UInt8_t opState;
  SE_UInt32_t opTime;
  List *Temperature;
  SE_TimeLink_t TimeLink;
} SE_DeviceStatus_t;

typedef struct {
  uint32_t _flags;
  char * href;
} SE_SelfDeviceLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_MirrorUsagePointListLink_t;

// #define SE_all_exists (1 << 0)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_UInt16_t all;
} SE_EndDeviceListLink_t;

// #define SE_TimeLink_exists (1 << 4)
// #define SE_UsagePointListLink_exists (1 << 5)
// #define SE_TariffProfileListLink_exists (1 << 6)
// #define SE_ResponseSetListLink_exists (1 << 7)
// #define SE_PrepaymentListLink_exists (1 << 8)
// #define SE_MessagingProgramListLink_exists (1 << 9)
// #define SE_FileListLink_exists (1 << 10)
// #define SE_DERProgramListLink_exists (1 << 11)
// #define SE_DemandResponseProgramListLink_exists (1 << 12)
// #define SE_CustomerAccountListLink_exists (1 << 13)
#define SE_SelfDeviceLink_exists (1 << 14)
#define SE_MirrorUsagePointListLink_exists (1 << 15)
#define SE_EndDeviceListLink_exists (1 << 16)
// #define SE_pollRate_exists (1 << 17)
typedef struct {
  uint32_t _flags;
  char * href;
  SE_CustomerAccountListLink_t CustomerAccountListLink;
  SE_DemandResponseProgramListLink_t DemandResponseProgramListLink;
  SE_DERProgramListLink_t DERProgramListLink;
  SE_FileListLink_t FileListLink;
  SE_MessagingProgramListLink_t MessagingProgramListLink;
  SE_PrepaymentListLink_t PrepaymentListLink;
  SE_ResponseSetListLink_t ResponseSetListLink;
  SE_TariffProfileListLink_t TariffProfileListLink;
  SE_TimeLink_t TimeLink;
  SE_UsagePointListLink_t UsagePointListLink;
  SE_UInt32_t pollRate;
  SE_EndDeviceListLink_t EndDeviceListLink;
  SE_MirrorUsagePointListLink_t MirrorUsagePointListLink;
  SE_SelfDeviceLink_t SelfDeviceLink;
} SE_DeviceCapability_t;

#define SE_AbstractDevice 0
#define SE_AccountBalance 1
#define SE_AccountBalanceLink 2
#define SE_AccountingUnit 3
#define SE_AccumulationBehaviourType 4
#define SE_ActiveBillingPeriodListLink 5
#define SE_ActiveCreditRegisterListLink 6
#define SE_ActiveDERControlListLink 7
#define SE_ActiveEndDeviceControlListLink 8
#define SE_ActiveFlowReservationListLink 9
#define SE_ActivePower 10
#define SE_ActiveProjectionReadingListLink 11
#define SE_ActiveSupplyInterruptionOverrideListLink 12
#define SE_ActiveTargetReadingListLink 13
#define SE_ActiveTextMessageListLink 14
#define SE_ActiveTimeTariffIntervalListLink 15
#define SE_AmpereHour 16
#define SE_ApparentPower 17
#define SE_ApplianceLoadReduction 18
#define SE_ApplianceLoadReductionType 19
#define SE_AppliedTargetReduction 20
#define SE_AssociatedDERProgramListLink 21
#define SE_AssociatedUsagePointLink 22
#define SE_BillingMeterReadingBase 23
#define SE_BillingPeriod 24
#define SE_BillingPeriodList 25
#define SE_BillingPeriodListLink 26
#define SE_BillingReading 27
#define SE_BillingReadingList 28
#define SE_BillingReadingListLink 29
#define SE_BillingReadingSet 30
#define SE_BillingReadingSetList 31
#define SE_BillingReadingSetListLink 32
#define SE_Charge 33
#define SE_ChargeKind 34
#define SE_CommodityType 35
#define SE_Condition 36
#define SE_Configuration 37
#define SE_ConfigurationLink 38
#define SE_ConnectStatusType 39
#define SE_ConsumptionBlockType 40
#define SE_ConsumptionTariffInterval 41
#define SE_ConsumptionTariffIntervalList 42
#define SE_ConsumptionTariffIntervalListLink 43
#define SE_CostKindType 44
#define SE_CreditRegister 45
#define SE_CreditRegisterList 46
#define SE_CreditRegisterListLink 47
#define SE_CreditStatusType 48
#define SE_CreditTypeChange 49
#define SE_CreditTypeType 50
#define SE_CurrencyCode 51
#define SE_CurrentDERProgramLink 52
#define SE_CurrentRMS 53
#define SE_CurveData 54
#define SE_CustomerAccount 55
#define SE_CustomerAccountLink 56
#define SE_CustomerAccountList 57
#define SE_CustomerAccountListLink 58
#define SE_CustomerAgreement 59
#define SE_CustomerAgreementList 60
#define SE_CustomerAgreementListLink 61
#define SE_DER 62
#define SE_DERAvailability 63
#define SE_DERAvailabilityLink 64
#define SE_DERCapability 65
#define SE_DERCapabilityLink 66
#define SE_DERControl 67
#define SE_DERControlBase 68
#define SE_DERControlList 69
#define SE_DERControlListLink 70
#define SE_DERControlResponse 71
#define SE_DERControlType 72
#define SE_DERCurve 73
#define SE_DERCurveLink 74
#define SE_DERCurveList 75
#define SE_DERCurveListLink 76
#define SE_DERCurveType 77
#define SE_DERLink 78
#define SE_DERList 79
#define SE_DERListLink 80
#define SE_DERProgram 81
#define SE_DERProgramLink 82
#define SE_DERProgramList 83
#define SE_DERProgramListLink 84
#define SE_DERSettings 85
#define SE_DERSettingsLink 86
#define SE_DERStatus 87
#define SE_DERStatusLink 88
#define SE_DERType 89
#define SE_DERUnitRefType 90
#define SE_DRLCCapabilities 91
#define SE_DataQualifierType 92
#define SE_DateTimeInterval 93
#define SE_DefaultDERControl 94
#define SE_DefaultDERControlLink 95
#define SE_DemandResponseProgram 96
#define SE_DemandResponseProgramLink 97
#define SE_DemandResponseProgramList 98
#define SE_DemandResponseProgramListLink 99
#define SE_DeviceCapability 100
#define SE_DeviceCapabilityLink 101
#define SE_DeviceCategoryType 102
#define SE_DeviceInformation 103
#define SE_DeviceInformationLink 104
#define SE_DeviceStatus 105
#define SE_DeviceStatusLink 106
#define SE_DrResponse 107
#define SE_DstRuleType 108
#define SE_DutyCycle 109
#define SE_EndDevice 110
#define SE_EndDeviceControl 111
#define SE_EndDeviceControlList 112
#define SE_EndDeviceControlListLink 113
#define SE_EndDeviceLink 114
#define SE_EndDeviceList 115
#define SE_EndDeviceListLink 116
#define SE_EnvironmentalCost 117
#define SE_Error 118
#define SE_Event 119
#define SE_EventStatus 120
#define SE_File 121
#define SE_FileLink 122
#define SE_FileList 123
#define SE_FileListLink 124
#define SE_FileStatus 125
#define SE_FileStatusLink 126
#define SE_FixedPointType 127
#define SE_FixedVar 128
#define SE_FlowDirectionType 129
#define SE_FlowReservationRequest 130
#define SE_FlowReservationRequestList 131
#define SE_FlowReservationRequestListLink 132
#define SE_FlowReservationResponse 133
#define SE_FlowReservationResponseList 134
#define SE_FlowReservationResponseListLink 135
#define SE_FlowReservationResponseResponse 136
#define SE_FreqDroopType 137
#define SE_FunctionSetAssignments 138
#define SE_FunctionSetAssignmentsBase 139
#define SE_FunctionSetAssignmentsList 140
#define SE_FunctionSetAssignmentsListLink 141
#define SE_HistoricalReading 142
#define SE_HistoricalReadingList 143
#define SE_HistoricalReadingListLink 144
#define SE_IEEE_802_15_4 145
#define SE_IPAddr 146
#define SE_IPAddrList 147
#define SE_IPAddrListLink 148
#define SE_IPInterface 149
#define SE_IPInterfaceList 150
#define SE_IPInterfaceListLink 151
#define SE_IdentifiedObject 152
#define SE_InverterStatusType 153
#define SE_KindType 154
#define SE_LLInterface 155
#define SE_LLInterfaceList 156
#define SE_LLInterfaceListLink 157
#define SE_Link 158
#define SE_List 159
#define SE_ListLink 160
#define SE_LoadShedAvailability 161
#define SE_LoadShedAvailabilityList 162
#define SE_LoadShedAvailabilityListLink 163
#define SE_LocalControlModeStatusType 164
#define SE_LocaleType 165
#define SE_LogEvent 166
#define SE_LogEventList 167
#define SE_LogEventListLink 168
#define SE_ManufacturerStatusType 169
#define SE_MessagingProgram 170
#define SE_MessagingProgramList 171
#define SE_MessagingProgramListLink 172
#define SE_MeterReading 173
#define SE_MeterReadingBase 174
#define SE_MeterReadingLink 175
#define SE_MeterReadingList 176
#define SE_MeterReadingListLink 177
#define SE_MirrorMeterReading 178
#define SE_MirrorMeterReadingList 179
#define SE_MirrorReadingSet 180
#define SE_MirrorUsagePoint 181
#define SE_MirrorUsagePointList 182
#define SE_MirrorUsagePointListLink 183
#define SE_Neighbor 184
#define SE_NeighborList 185
#define SE_NeighborListLink 186
#define SE_Notification 187
#define SE_NotificationList 188
#define SE_NotificationListLink 189
#define SE_Offset 190
#define SE_OneHourRangeType 191
#define SE_OperationalModeStatusType 192
#define SE_PENType 193
#define SE_PEVInfo 194
#define SE_PINType 195
#define SE_PerCent 196
#define SE_PhaseCode 197
#define SE_PowerConfiguration 198
#define SE_PowerFactor 199
#define SE_PowerOfTenMultiplierType 200
#define SE_PowerSourceType 201
#define SE_PowerStatus 202
#define SE_PowerStatusLink 203
#define SE_PrepayModeType 204
#define SE_PrepayOperationStatus 205
#define SE_PrepayOperationStatusLink 206
#define SE_Prepayment 207
#define SE_PrepaymentLink 208
#define SE_PrepaymentList 209
#define SE_PrepaymentListLink 210
#define SE_PriceResponse 211
#define SE_PriceResponseCfg 212
#define SE_PriceResponseCfgList 213
#define SE_PriceResponseCfgListLink 214
#define SE_PrimacyType 215
#define SE_PriorityType 216
#define SE_ProjectionReading 217
#define SE_ProjectionReadingList 218
#define SE_ProjectionReadingListLink 219
#define SE_RPLInstance 220
#define SE_RPLInstanceList 221
#define SE_RPLInstanceListLink 222
#define SE_RPLSourceRoutes 223
#define SE_RPLSourceRoutesList 224
#define SE_RPLSourceRoutesListLink 225
#define SE_RandomizableEvent 226
#define SE_RateComponent 227
#define SE_RateComponentLink 228
#define SE_RateComponentList 229
#define SE_RateComponentListLink 230
#define SE_ReactivePower 231
#define SE_Reading 232
#define SE_ReadingBase 233
#define SE_ReadingLink 234
#define SE_ReadingList 235
#define SE_ReadingListLink 236
#define SE_ReadingSet 237
#define SE_ReadingSetBase 238
#define SE_ReadingSetList 239
#define SE_ReadingSetListLink 240
#define SE_ReadingType 241
#define SE_ReadingTypeLink 242
#define SE_RealEnergy 243
#define SE_Registration 244
#define SE_RegistrationLink 245
#define SE_RequestStatus 246
#define SE_Resource 247
#define SE_RespondableIdentifiedObject 248
#define SE_RespondableResource 249
#define SE_RespondableSubscribableIdentifiedObject 250
#define SE_Response 251
#define SE_ResponseList 252
#define SE_ResponseListLink 253
#define SE_ResponseSet 254
#define SE_ResponseSetList 255
#define SE_ResponseSetListLink 256
#define SE_RoleFlagsType 257
#define SE_SFDIType 258
#define SE_SelfDevice 259
#define SE_SelfDeviceLink 260
#define SE_ServiceChange 261
#define SE_ServiceKind 262
#define SE_ServiceStatusType 263
#define SE_ServiceSupplier 264
#define SE_ServiceSupplierLink 265
#define SE_ServiceSupplierList 266
#define SE_SetPoint 267
#define SE_SignedPerCent 268
#define SE_SignedRealEnergy 269
#define SE_StateOfChargeStatusType 270
#define SE_StorageModeStatusType 271
#define SE_SubscribableIdentifiedObject 272
#define SE_SubscribableList 273
#define SE_SubscribableResource 274
#define SE_Subscription 275
#define SE_SubscriptionBase 276
#define SE_SubscriptionList 277
#define SE_SubscriptionListLink 278
#define SE_SupplyInterruptionOverride 279
#define SE_SupplyInterruptionOverrideList 280
#define SE_SupplyInterruptionOverrideListLink 281
#define SE_SupportedLocale 282
#define SE_SupportedLocaleList 283
#define SE_SupportedLocaleListLink 284
#define SE_TOUType 285
#define SE_TargetReading 286
#define SE_TargetReadingList 287
#define SE_TargetReadingListLink 288
#define SE_TargetReduction 289
#define SE_TariffProfile 290
#define SE_TariffProfileLink 291
#define SE_TariffProfileList 292
#define SE_TariffProfileListLink 293
#define SE_Temperature 294
#define SE_TextMessage 295
#define SE_TextMessageList 296
#define SE_TextMessageListLink 297
#define SE_TextResponse 298
#define SE_Time 299
#define SE_TimeConfiguration 300
#define SE_TimeLink 301
#define SE_TimeOffsetType 302
#define SE_TimeTariffInterval 303
#define SE_TimeTariffIntervalList 304
#define SE_TimeTariffIntervalListLink 305
#define SE_TimeType 306
#define SE_UnitType 307
#define SE_UnitValueType 308
#define SE_UnsignedFixedPointType 309
#define SE_UomType 310
#define SE_UsagePoint 311
#define SE_UsagePointBase 312
#define SE_UsagePointLink 313
#define SE_UsagePointList 314
#define SE_UsagePointListLink 315
#define SE_VersionType 316
#define SE_VoltageRMS 317
#define SE_WattHour 318
#define SE_loWPAN 319
#define SE_mRIDType 320

